// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARDHqasoTkzw4A8v54ELKTtskXq7DjCDE',
    appId: '1:176318483430:web:e885708c78cb9c3f5f2427',
    messagingSenderId: '176318483430',
    projectId: 'firebase-flutter-dp',
    authDomain: 'fir-flutter-dp.firebaseapp.com',
    storageBucket: 'firebase-flutter-dp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiLVb9fkaczJcONKC2fRX7_TQ72370Ztk',
    appId: '1:176318483430:android:b75f735d4de246905f2427',
    messagingSenderId: '176318483430',
    projectId: 'firebase-flutter-dp',
    storageBucket: 'firebase-flutter-dp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCW3LR4eW6RUqAjCFhq_7Ia2X6iHsefkNE',
    appId: '1:176318483430:ios:a2a432a75e5ce65b5f2427',
    messagingSenderId: '176318483430',
    projectId: 'firebase-flutter-dp',
    storageBucket: 'firebase-flutter-dp.appspot.com',
    iosBundleId: 'com.example.firebaseFlutter',
  );
}
